#+TITLE: Algoritmo genético com representação real
#+SUBTITLE: Algoritmos Bioinspirados
#+AUTHOR: Heitor Lourenço Werneck
#+EMAIL: heitorwerneck@hotmail.com
#+DATE: 
#+LANGUAGE: pt
#+OPTIONS: ^:nil email:nil author:nil toc:nil
#+LATEX_HEADER: \author{Heitor Lourenço Werneck \\github.com/heitor57\\{\href{mailto:heitorwerneck@hotmail.com}{heitorwerneck@hotmail.com}}}
#+LATEX_HEADER: \usepackage[AUTO]{babel}
# mathtools ja inclui amsmath #+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{mathtools}
#+LATEX_HEADER: \usepackage[binary-units=true]{siunitx}
#+LATEX_HEADER: \usepackage[top=0.5cm,bottom=1.5cm,left=2cm,right=2cm]{geometry}
#+LATEX_HEADER: \usepackage{mdframed}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{algpseudocode}
#+LATEX_HEADER: \usepackage[Algoritmo]{algorithm}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{colortbl}
#+LATEX_HEADER: \usepackage{graphicx,wrapfig,lipsum}
#+LATEX_HEADER: \usepackage{pifont}
#+LATEX_HEADER: \usepackage{subfigure}
#+LATEX_HEADER: \usepackage{rotating}
#+LATEX_HEADER: \usepackage{multirow}
#+LATEX_HEADER: \usepackage{tablefootnote}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{dblfloatfix}
#+LATEX_HEADER: \usepackage{color, colortbl}
#+LATEX_HEADER: \usepackage{chngcntr}
#+LATEX_HEADER: \usepackage{epstopdf}
#+latex_class_options: [11pt]

#+PROPERTY: header-args :eval no-export
#+BEGIN_EXPORT latex
\usetikzlibrary{arrows, fit, matrix, positioning, shapes, backgrounds,intersections}
\usetikzlibrary{decorations.pathreplacing}
\usetikzlibrary{automata, positioning, arrows}
\usetikzlibrary{calc}

\definecolor{bg}{rgb}{0.95,0.95,0.95}
\BeforeBeginEnvironment{minted}{\begin{mdframed}[backgroundcolor=bg]}
\AfterEndEnvironment{minted}{\end{mdframed}}
\numberwithin{equation}{section}
\algnewcommand{\IfThenElse}[3]{% \IfThenElse{<if>}{<then>}{<else>}
  \State \algorithmicif\ #1\ \algorithmicthen\ #2\ \algorithmicelse\ #3}

% Define block styles
\tikzstyle{decision} = [diamond, draw, fill=blue!20, 
    text width=4.5em, text badly centered, node distance=3cm, inner sep=0pt]
\tikzstyle{block} = [rectangle, draw, fill=blue!20, 
    text width=5em, text centered, rounded corners, minimum height=4em]
\tikzstyle{line} = [draw, -latex']
\tikzstyle{cloud} = [ellipse, draw, fill=red!20, 
    text width=5em, text centered, rounded corners, minimum height=2em]
%\tikzstyle{cloud} = [draw, ellipse,fill=red!20, node distance=3.5cm,
%    minimum height=2em]


\lstset{
  basicstyle=\ttfamily,
  columns=fullflexible,
  frame=single,
  breaklines=true,
  postbreak=\mbox{\textcolor{red}{$\hookrightarrow$}\space},
}
\DeclarePairedDelimiter\ceil{\lceil}{\rceil}
\DeclarePairedDelimiter\floor{\lfloor}{\rfloor}

% Numbering fix
\counterwithout{equation}{section} % undo numbering system provided by phstyle.cls
%\counterwithin{equation}{chapter}  % implement desired numbering system

#+END_EXPORT


* Introdução
Algoritmos genéticos se referem a uma família de modelos computacionais inspirados na evolução(seleção natural e genética). Esses algoritmos representam a solução problema atráves de estruturas semelhantes a cromossomos e aplicam operadores de recombinação para preservar os dados/informações vitais cite:whitley94_genet_algor_tutor,goldenberg1989genetic. Normalmente um algoritmo genético será baseado em população e usará operadores de seleção e recombinação para buscar uma solução no espaço de busca cite:whitley94_genet_algor_tutor.

Algoritmos genéticos são utilizados em diversos cenários pela natureza generalista de seu modelo, como por exemplo: sistemas de recomendação cite:naruchitparames2011friend,silva2010graph; visão computacional cite:gong2004quadtree; robôs de limpeza cite:yakoubi2016path; recuperação de informação cite:vrajitoru1998crossover e agendamento de voos cite:lee2007multi.

Os algoritmos genéticos também possuem a capacidade de fazer /exploitation/ e /exploration/ que são características de modelos estado da arte em diversas áreas, como por exemplo: /Multi-Armed Bandits/; Nuvem de partículas e outros. Uma característica extremamente importante para diversos cenários.

Esse trabalho consiste na implementação e análise de um algoritmo genético com representação real para solução de um problema de otimização de uma função.

* Problema

O problema é simples e consiste na minimização da função da equação ref:eq:of. 
#+begin_export latex
\begin{equation}
\label{eq:of}
F_o(x) = -20\epsilon^{-0.2}\sqrt{\frac{1}{n}\sum x_i^2} - \epsilon^{\frac{1}{n}\sum cos(2\pi x_i)} + 20 + \epsilon
\end{equation}
#+end_export

É importante notar que como o problema será representado em um sistema computacional como um número real então o espaço de busca terá $2^{\text{bits}}$ possibilidades de solução. Isso mostra que é um problema difícil, pois possui uma complexidade de ordem exponencial no espaço de soluções, por isso é importante usar alguma heurística ou meta-heurística (que no caso é algoritmo genético) para solucionar esse problema caso não tenha solução analítica viável.

* Solução

As estruturas básicas para o algoritmo foram determinadas da seguinte forma: os genes são números reais e não precisam de nenhuma transformação para serem aplicados na equação eqref:eq:of, essa representação é, em comparação com o número de bits utilizado na outra representação do trabalho anterior, muito mais complexa em termos de quantidade de possíveis soluções (espaço de busca bem maior), claro que o espaço de busca poderia ser ainda maior com a representação por bits, porém em termos de eficiência na busca está implementação é mais efetiva. O espaço de busca continua sendo discreto porém bem maior do que com os números de bits utilizados no trabalho anterior. Como a linguagem utilizada foi Python e nessa linguagem o tipo de dado utilizado para representar um gene (o número real) foi o float. O float em Python é majoritariamente mapeado para IEEE-754 “precisão dupla” nas plataformas, inclusive a usada para fazer o experimento.

Para guiar a busca o estado de busca de soluções foi dentro do domínio $max_{value} = -2$ e $min_{value} = 2$ (i.e. $x \in [min_{value},max_{value}]$), isso por que foi analisado que dentro dessa espaço há bons valores para minimização da função e possivelmente a solução ótima do problema.

A estratégia de seleção de pais utilizada foi a roleta, tal que um indivíduo é selecionado a partir de um procedimento que define uma probabilidade de ser escolhido para cada indivíduo com base em seu fitness e após isso um indivíduo é escolhido a partir desse conjunto de probabilidades. Para a atribuição das probabilidades é necessário transformar o fitness, pois como é um problema de minimização então os indíviduos com menores fitness devem ser os indíviduos mais priorizados, para isso cada fitness foi aplicado em $f(x) = 1/(x+\text{Menor float positivo da linguagem})$ após isso o conjunto de probabilidades é construido $\{\frac{f(x)}{\sum_{y\in fitnesses} f(y)}: x \in fitnesses \}$. 

Para a intensificação do espaço de busca foi definido duas estratégias de cruzamento, sendo elas: $BLX\text{-}\alpha$ que sorteia um número aleatório de uma distribuição uniforme dentro de um intervalo que é delimitado a partir dos menores e maiores genes e variados a partir da diferença do produto da diferença dos genes dos pais com \alpha e esse intervalo é limitado pelo intervalo $[min_{value},max_{value}]$, ou seja, os valores não podem passar desses limites e se passam se transformam nos limites passados; $BLX\text{-}\alpha\beta$ que sorteia um número aleatório de uma distribuição uniforme dentro de um intervalo que varia dependendo de qual pai tem o maior gene assim o parâmetro $\beta$ limita o espaço de busca na direção do pior fitness e o $\alpha$ limita o espaço de busca na direção do melhor fitness, normalmente $\alpha>\beta$, e os intervalos também são limitados em $[min_{value},max_{value}]$.

Quando a taxa de cruzamento não é de 100% então indivíduos da população anterior são adicionados aleatoriamente a nova população até o limite de indivíduos.

Para mutação dos indivíduos foi utilizado um parâmetro de taxa de mutação que define a probabilidade de um indivíduo ser mutado. A mutação foi definida como o sorteio de um gene para ter o valor trocado através de outro sorteio de um valor dentro do intervalo $[min_{value},max_{value}]$.

Para garantir uma curva de convergência sem oscilação e constante busca a melhorar os valores o elitismo foi aplicado e definido como a preservação do indivíduo com maior aptidão da população anterior, ele substitui um indivíduo aleatório da nova população. 

Os parâmetros mais relevantes são mostrados na tabela a seguir, através dele o algoritmo genético pode ser ajustado para obter boas soluções, fora as mudanças nos operadores de seleção (i.e., $BLX\text{-}\alpha$ e $BLX\text{-}\alpha\beta$), cruzamento e mutação (aqui, no caso, não foram estudadas outras variações).

#+CAPTION: Parâmetros
| Parâmetro                | Descrição                                                           |
| $min_{value}$            | Limite inferior do espaço de busca                                  |
| $max_{value}$            | Limite superior do espaço de busca                                  |
| #População               | Quantidade de indivíduos                                            |
| #Gerações                | Quantidade de gerações                                              |
| Taxa de cruzamento       | Taxa do número de indivíduos que vão cruzar                         |
| Probabilidade de mutação | Probabilidade da mutação de um indivíduo                            |
| Elitismo                 | Se irá usar a preservação do melhor indivíduo da população anterior |


Uma visão geral de como o algoritmo funciona é dado no algoritmo ref:alg:ag.
#+begin_export latex
\begin{algorithm}
  \caption{Algoritmo genético}
  \label{alg:ag}
  \begin{algorithmic}[1]
  \State Inicia a população com cromossomos aleatórios
  \For{$i=1$ to \#Gerações}
  \State Cruza os indivíduos utilizando a roleta para selecionar os pais e de acordo com a taxa de cruzamento
  \State Completa o número de índivíduos com indivíduos aleatórios da população anterior caso a taxa de cruzamento não seja de 100\%
  \State Faz a mutação dos indivíduos da população atual de acordo com a probabilidade de mutação
  \If{Elitismo}
  \State Seleciona o melhor indivíduo da população anterior e substitui um indíviduo aleatório da geração corrente
  \EndIf
  \EndFor
  \end{algorithmic}
\end{algorithm}
#+end_export


* Resultados

Para a análise de resultados foi utilizado 10 execuções para cada conjunto de parâmetro, devido a natureza probabilística do problema é importante sempre sumarizar os resultados de varias execuções para ter uma ideia do resultado esperado.

Também é preciso definir os parâmetros dos operadores de cruzamento, são eles:
$BLX\text{-}\alpha$ com $\alpha = 0.5$ e $BLX\text{-}\alpha\beta$ com $\alpha = 0.75, \beta = 0.25$.

** Calibragem de parâmetros

Para começo da análise um experimento fatorial completo será realizado. Os valores para busca estão indicados tabela a seguir com o domínio de busca para cada parâmetro (tabela ref:tbl:hyperparameter).

#+CAPTION: Domínio de busca de cada parâmetro.
#+NAME: tbl:hyperparameter
|--------------------------+-------------------------------------------------|
| Operador de cruzamento   | {$BLX\text{-}\alpha$, $BLX\text{-}\alpha\beta$} |
| Elitismo                 | {False, True}                                   |
| #Gerações                | {25,50,100}                                     |
| #População               | {25,50,100}                                     |
| Taxa de cruzamento       | {0.6, 0.8, 1.0}                                 |
| Probabilidade de mutação | {0.01, 0.05, 0.1}                               |
|--------------------------+-------------------------------------------------|


Depois da execução o top-25 de parâmetros são descritos na tabela ref:tbl:parameters, onde $\mu$ denota a média e $\sigma$ denota o desvio padrão das 10 execuções. Nessa tabela os dados são obtidos pela ultima geração de cada execução.

É possível ver que diversos conjuntos de parâmetros conseguiram chegar na mesma melhor solução, isso mostra que diversas combinações de parâmetros são viáveis para otimização desse problema. Também é interessante notar que diversas execuções para um mesmo conjunto de parâmetros conseguiram chegar no mesmo resultado, assim obtendo um desvio padrão de 0 para diversas soluções, mostrando resultados bem consistentes.

A aptidão média no geral é bem maior relativamente a melhor aptidão, isso pois eventualmente indivíduos terão genes mutados e isso causa uma oscilação na aptidão média, porém uma medida mais robusta contra outliers mostra que grande parte das execuções tiveram um bom balanço da aptidão da população. Então é importante usar uma medida robusta a outliers para não se ter um falso julgamento na avaliação da execução de algoritmos genéticos. 

Tanto soluções sem elitismo e com elitismo conseguiram obter soluções ótimas, soluções com elitismo são mais abertas a diversificação da população (i.e., mais mutação), pois com a preservação do melhor indivíduo buscas diversas são mais seguras já que não correm o risco de perder bons indíviduos. Mas também é interessante notar que os resultados sem elitismo também conseguem chegar na solução ótima, isso porque atráves de cruzamento os pais ainda conseguem propagar seus genes e indíviduos com mais aptidão possuem mais probabilidade de cruzamento. Isso pode ser notado pois grande parte das melhores soluções sem elitismo possuem uma taxa de cruzamento maior ou igual a 0.8 (também existe exceção porém utilizando $BLX\text{-}\alpha\beta$ que direciona a busca para o melhor indivíduo). Também na maioria das soluções com elitismo e sem elitismo as médias de aptidão média são bem próximas.

Outro ponto a se notar é que grande parte das soluções possuem uma taxa de cruzamento maior que 0.6, isso mostra que para esse problema é importante um alto nivel de intensificação no espaço de busca, isso pode se dever ao espaço de busca ser relativamente grande comparado com o trabalho com representação binária que um espaço de busca muito menor foi especificado.

As taxas de mutação foram bem diversas, elas conseguem combinar com os parâmetros de diversas maneiras diferentes podendo aumentar seu valor (assim aumentando a diversificação) e aumentando intensificação atráves de outro parâmetro para balancear.

Os dois operadores de cruzamento conseguiram ter soluções ótimas, porém é interessante notar que um operador funciona melhor com certos cenários como discutido anteriormente. No geral o $BLX\text{-}\alpha\beta$ conseguiu cobrir mais casos de parâmetros devido a sua busca mais direcionada ao melhor indivíduo.

#+begin_export latex
\begin{table}
\footnotesize
\caption{Top-25 Parâmetros e seus resultados}
\label{tbl:parameters}
  \makebox[\textwidth]{
\begin{tabular}{|p{0.88cm}|l|p{2cm}|l|l|l|l|l|l|l|l|l|}
Taxa de cruzamento & \rotatebox[origin=c]{45}{Elitismo} & Probabilidade de mutação & \rotatebox[origin=c]{45}{Cruzamento} & \rotatebox[origin=c]{45}{\#Gerações} & \rotatebox[origin=c]{45}{\#População} & \multicolumn{2}{c}{Melhor aptidão} & \multicolumn{2}{|c|}{Aptidão média} & \multicolumn{2}{c|}{Aptidão mediana}\\
 & & & & & & \multicolumn{1}{c|}{$\mu$}& \multicolumn{1}{c|}{$\sigma$} & \multicolumn{1}{|c|}{$\mu$}& \multicolumn{1}{c|}{$\sigma$} &\multicolumn{1}{c|}{$\mu$}& \multicolumn{1}{c|}{$\sigma$} \\
0.8 & False & 0.10 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.439 & 0.137 & 4.441e-16 & 0.000e+0\\
0.8 & False & 0.10 & $BLX\text{-}\alpha$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.424 & 0.123 & 4.441e-16 & 0.000e+0\\
0.8 & True & 0.05 & $BLX\text{-}\alpha$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.221 & 0.127 & 4.441e-16 & 0.000e+0\\
0.8 & True & 0.10 & $BLX\text{-}\alpha\beta$ & 100 & 50 & 4.441e-16 & 0.000e+0 & 0.450 & 0.223 & 4.441e-16 & 0.000e+0\\
0.8 & True & 0.10 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.467 & 0.112 & 4.441e-16 & 0.000e+0\\
1.0 & False & 0.01 & $BLX\text{-}\alpha\beta$ & 50 & 100 & 4.441e-16 & 0.000e+0 & 0.065 & 0.036 & 4.441e-16 & 0.000e+0\\
1.0 & False & 0.01 & $BLX\text{-}\alpha\beta$ & 100 & 50 & 4.441e-16 & 0.000e+0 & 0.033 & 0.073 & 4.441e-16 & 0.000e+0\\
1.0 & False & 0.01 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.030 & 0.044 & 4.441e-16 & 0.000e+0\\
1.0 & False & 0.05 & $BLX\text{-}\alpha$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.181 & 0.114 & 4.441e-16 & 0.000e+0\\
1.0 & False & 0.05 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.139 & 0.057 & 4.441e-16 & 0.000e+0\\
1.0 & False & 0.10 & $BLX\text{-}\alpha$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.390 & 0.106 & 4.441e-16 & 0.000e+0\\
1.0 & False & 0.10 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.364 & 0.097 & 4.441e-16 & 0.000e+0\\
1.0 & True & 0.01 & $BLX\text{-}\alpha$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.041 & 0.034 & 4.441e-16 & 0.000e+0\\
1.0 & True & 0.01 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.033 & 0.037 & 4.441e-16 & 0.000e+0\\
1.0 & True & 0.05 & $BLX\text{-}\alpha\beta$ & 50 & 100 & 4.441e-16 & 0.000e+0 & 0.158 & 0.074 & 4.441e-16 & 0.000e+0\\
1.0 & True & 0.05 & $BLX\text{-}\alpha\beta$ & 100 & 25 & 4.441e-16 & 0.000e+0 & 0.189 & 0.179 & 4.441e-16 & 0.000e+0\\
1.0 & True & 0.05 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.180 & 0.116 & 4.441e-16 & 0.000e+0\\
1.0 & True & 0.10 & $BLX\text{-}\alpha\beta$ & 50 & 100 & 4.441e-16 & 0.000e+0 & 0.392 & 0.091 & 4.441e-16 & 0.000e+0\\
0.8 & False & 0.05 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.223 & 0.114 & 4.441e-16 & 0.000e+0\\
0.6 & False & 0.10 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.632 & 0.176 & 4.441e-16 & 0.000e+0\\
1.0 & True & 0.10 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.271 & 0.087 & 4.441e-16 & 0.000e+0\\
0.6 & False & 0.01 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 4.441e-16 & 0.000e+0 & 0.068 & 0.052 & 4.441e-16 & 0.000e+0\\
1.0 & True & 0.05 & $BLX\text{-}\alpha$ & 100 & 100 & 7.993e-16 & 1.123e-15 & 0.202 & 0.107 & 7.993e-16 & 1.123e-15\\
0.6 & True & 0.01 & $BLX\text{-}\alpha\beta$ & 100 & 100 & 7.993e-16 & 1.123e-15 & 0.035 & 0.034 & 7.993e-16 & 1.123e-15\\
1.0 & True & 0.01 & $BLX\text{-}\alpha\beta$ & 50 & 100 & 7.993e-16 & 1.123e-15 & 0.024 & 0.049 & 7.993e-16 & 1.123e-15\\
\end{tabular}
}
\end{table}

#+end_export

* Conclusão

Com esse trabalho foi possível fazer a análise detalhada do comportamento de um modelo de algoritmo genético. Atráves de multiplos gráficos os parâmetros do modelo foram análisados. Como o problema a ser tratado é bem simples o algoritmo majoritariamente consegue achar o ponto ótimo do domínio.

bibliography:doc.bib
bibliographystyle:plain
