num_pop: # Population size
 default: 50
 pretty_name: "#Population"
num_generations: # Number of generations
 default: 50
 pretty_name: "#Generations"
num_genes: # Number of genes
 default: 2
 pretty_name: "#Genes"
cross_rate: # Rate of individuals who are going to be crossed instead of being preserved from previous generation, commonly it is going to stay in 1.0 but to be more flexible it is presented as a variable
 default: 1.0
 pretty_name: "Cross rate"
elitism: 
 default: True
 pretty_name: "Elitism"
mutation_rate: 
 default: 0.01
 pretty_name: "Mutation rate"
min_value: # Linear space minimum number
 default: -2.0
 pretty_name: "Min value"
max_value: # Linear space maximum number
 default: 2.0
 pretty_name: "Max value"
eid: 
 default: 1
 pretty_name: "Execution ID"
